[package]
name = "uni-jena-suite"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "src/library.typ"

authors = ["Justin Jakull <justin@jakull.de>"]

repository = "https://github.com/piepert/grape-suite"
license = "MIT"

keywords = ["clean", "blue", "minimal", "paper", "jena"]
description = "Library of templates for exams, seminar papers, homeworks, etc. based on grape-suite, designed for uni-jena.de corporate deisgn"
categories = ["layout", "paper", "presentation"]
exclude = ["/img/*", "/examples/*"]

[template]
path = "src/template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"